package com.dmsistemas.poliza.model;
// Generated 26/05/2019 12:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Movpoliza generated by hbm2java
 */
public class Movpoliza  implements java.io.Serializable {


     private int numReg;
     private Integer numCheque;
     private Date fecha;
     private Date fechaSistema;
     private Integer procesado;

    public Movpoliza() {
    }

	
    public Movpoliza(int numReg, Date fecha) {
        this.numReg = numReg;
        this.fecha = fecha;
    }
    public Movpoliza(int numReg, Integer numCheque, Date fecha, Date fechaSistema, Integer procesado) {
       this.numReg = numReg;
       this.numCheque = numCheque;
       this.fecha = fecha;
       this.fechaSistema = fechaSistema;
       this.procesado = procesado;
    }
   
    public int getNumReg() {
        return this.numReg;
    }
    
    public void setNumReg(int numReg) {
        this.numReg = numReg;
    }
    public Integer getNumCheque() {
        return this.numCheque;
    }
    
    public void setNumCheque(Integer numCheque) {
        this.numCheque = numCheque;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaSistema() {
        return this.fechaSistema;
    }
    
    public void setFechaSistema(Date fechaSistema) {
        this.fechaSistema = fechaSistema;
    }
    public Integer getProcesado() {
        return this.procesado;
    }
    
    public void setProcesado(Integer procesado) {
        this.procesado = procesado;
    }




}


