package com.dmsistemas.poliza.model;
// Generated 26/05/2019 12:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Movs04 generated by hbm2java
 */
public class Movs04  implements java.io.Serializable {


     private int numReg;
     private String cveConcep;
     private Integer conPart;
     private Integer numCheque;
     private String ref1;
     private String ref2;
     private String status;
     private Date fecha;
     private Date FCobro;
     private String bandPrn;
     private String bandCont;
     private String actSae;
     private String numPol;
     private String tipPol;
     private Integer saeCoi;
     private double montoTot;
     private Double montoIvaTot;
     private Double montoExt;
     private Integer moneda;
     private Double TCambio;
     private Integer hora;
     private String clpv;
     private Integer ctaTransf;
     private Date fechaLiq;
     private Date fechaPol;
     private Integer cveInst;
     private String mondifsae;
     private Double tcambiosae;
     private String rfc;
     private Integer concSae;
     private String solicit;
     private Integer transCoi;
     private Integer intsaenoi;
     private String XObser;
     private int factor;
     private int formapago;
     private String anombrede;
     private String asociado;
     private String ctaContabAsoc;
     private Integer revisado;
     private String prioridad;
     private Integer docAsoc;
     private Integer resaltar;
     private Integer anticipo;
     private Integer idtransf;
     private String sucursal;
     private String cuenta;
     private String clabe;
     private Integer multiClpv;
     private String cveBancoAsoc;
     private Integer numConcAuto;
     private Integer coiDepto;
     private Integer coiCcostos;
     private Integer coiProyecto;
     private Set parmovs04s = new HashSet(0);

    public Movs04() {
    }

	
    public Movs04(int numReg, String cveConcep, String status, Date fecha, Date FCobro, double montoTot, int factor, int formapago, String asociado) {
        this.numReg = numReg;
        this.cveConcep = cveConcep;
        this.status = status;
        this.fecha = fecha;
        this.FCobro = FCobro;
        this.montoTot = montoTot;
        this.factor = factor;
        this.formapago = formapago;
        this.asociado = asociado;
    }
    public Movs04(int numReg, String cveConcep, Integer conPart, Integer numCheque, String ref1, String ref2, String status, Date fecha, Date FCobro, String bandPrn, String bandCont, String actSae, String numPol, String tipPol, Integer saeCoi, double montoTot, Double montoIvaTot, Double montoExt, Integer moneda, Double TCambio, Integer hora, String clpv, Integer ctaTransf, Date fechaLiq, Date fechaPol, Integer cveInst, String mondifsae, Double tcambiosae, String rfc, Integer concSae, String solicit, Integer transCoi, Integer intsaenoi, String XObser, int factor, int formapago, String anombrede, String asociado, String ctaContabAsoc, Integer revisado, String prioridad, Integer docAsoc, Integer resaltar, Integer anticipo, Integer idtransf, String sucursal, String cuenta, String clabe, Integer multiClpv, String cveBancoAsoc, Integer numConcAuto, Integer coiDepto, Integer coiCcostos, Integer coiProyecto, Set parmovs04s) {
       this.numReg = numReg;
       this.cveConcep = cveConcep;
       this.conPart = conPart;
       this.numCheque = numCheque;
       this.ref1 = ref1;
       this.ref2 = ref2;
       this.status = status;
       this.fecha = fecha;
       this.FCobro = FCobro;
       this.bandPrn = bandPrn;
       this.bandCont = bandCont;
       this.actSae = actSae;
       this.numPol = numPol;
       this.tipPol = tipPol;
       this.saeCoi = saeCoi;
       this.montoTot = montoTot;
       this.montoIvaTot = montoIvaTot;
       this.montoExt = montoExt;
       this.moneda = moneda;
       this.TCambio = TCambio;
       this.hora = hora;
       this.clpv = clpv;
       this.ctaTransf = ctaTransf;
       this.fechaLiq = fechaLiq;
       this.fechaPol = fechaPol;
       this.cveInst = cveInst;
       this.mondifsae = mondifsae;
       this.tcambiosae = tcambiosae;
       this.rfc = rfc;
       this.concSae = concSae;
       this.solicit = solicit;
       this.transCoi = transCoi;
       this.intsaenoi = intsaenoi;
       this.XObser = XObser;
       this.factor = factor;
       this.formapago = formapago;
       this.anombrede = anombrede;
       this.asociado = asociado;
       this.ctaContabAsoc = ctaContabAsoc;
       this.revisado = revisado;
       this.prioridad = prioridad;
       this.docAsoc = docAsoc;
       this.resaltar = resaltar;
       this.anticipo = anticipo;
       this.idtransf = idtransf;
       this.sucursal = sucursal;
       this.cuenta = cuenta;
       this.clabe = clabe;
       this.multiClpv = multiClpv;
       this.cveBancoAsoc = cveBancoAsoc;
       this.numConcAuto = numConcAuto;
       this.coiDepto = coiDepto;
       this.coiCcostos = coiCcostos;
       this.coiProyecto = coiProyecto;
       this.parmovs04s = parmovs04s;
    }
   
    public int getNumReg() {
        return this.numReg;
    }
    
    public void setNumReg(int numReg) {
        this.numReg = numReg;
    }
    public String getCveConcep() {
        return this.cveConcep;
    }
    
    public void setCveConcep(String cveConcep) {
        this.cveConcep = cveConcep;
    }
    public Integer getConPart() {
        return this.conPart;
    }
    
    public void setConPart(Integer conPart) {
        this.conPart = conPart;
    }
    public Integer getNumCheque() {
        return this.numCheque;
    }
    
    public void setNumCheque(Integer numCheque) {
        this.numCheque = numCheque;
    }
    public String getRef1() {
        return this.ref1;
    }
    
    public void setRef1(String ref1) {
        this.ref1 = ref1;
    }
    public String getRef2() {
        return this.ref2;
    }
    
    public void setRef2(String ref2) {
        this.ref2 = ref2;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFCobro() {
        return this.FCobro;
    }
    
    public void setFCobro(Date FCobro) {
        this.FCobro = FCobro;
    }
    public String getBandPrn() {
        return this.bandPrn;
    }
    
    public void setBandPrn(String bandPrn) {
        this.bandPrn = bandPrn;
    }
    public String getBandCont() {
        return this.bandCont;
    }
    
    public void setBandCont(String bandCont) {
        this.bandCont = bandCont;
    }
    public String getActSae() {
        return this.actSae;
    }
    
    public void setActSae(String actSae) {
        this.actSae = actSae;
    }
    public String getNumPol() {
        return this.numPol;
    }
    
    public void setNumPol(String numPol) {
        this.numPol = numPol;
    }
    public String getTipPol() {
        return this.tipPol;
    }
    
    public void setTipPol(String tipPol) {
        this.tipPol = tipPol;
    }
    public Integer getSaeCoi() {
        return this.saeCoi;
    }
    
    public void setSaeCoi(Integer saeCoi) {
        this.saeCoi = saeCoi;
    }
    public double getMontoTot() {
        return this.montoTot;
    }
    
    public void setMontoTot(double montoTot) {
        this.montoTot = montoTot;
    }
    public Double getMontoIvaTot() {
        return this.montoIvaTot;
    }
    
    public void setMontoIvaTot(Double montoIvaTot) {
        this.montoIvaTot = montoIvaTot;
    }
    public Double getMontoExt() {
        return this.montoExt;
    }
    
    public void setMontoExt(Double montoExt) {
        this.montoExt = montoExt;
    }
    public Integer getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Integer moneda) {
        this.moneda = moneda;
    }
    public Double getTCambio() {
        return this.TCambio;
    }
    
    public void setTCambio(Double TCambio) {
        this.TCambio = TCambio;
    }
    public Integer getHora() {
        return this.hora;
    }
    
    public void setHora(Integer hora) {
        this.hora = hora;
    }
    public String getClpv() {
        return this.clpv;
    }
    
    public void setClpv(String clpv) {
        this.clpv = clpv;
    }
    public Integer getCtaTransf() {
        return this.ctaTransf;
    }
    
    public void setCtaTransf(Integer ctaTransf) {
        this.ctaTransf = ctaTransf;
    }
    public Date getFechaLiq() {
        return this.fechaLiq;
    }
    
    public void setFechaLiq(Date fechaLiq) {
        this.fechaLiq = fechaLiq;
    }
    public Date getFechaPol() {
        return this.fechaPol;
    }
    
    public void setFechaPol(Date fechaPol) {
        this.fechaPol = fechaPol;
    }
    public Integer getCveInst() {
        return this.cveInst;
    }
    
    public void setCveInst(Integer cveInst) {
        this.cveInst = cveInst;
    }
    public String getMondifsae() {
        return this.mondifsae;
    }
    
    public void setMondifsae(String mondifsae) {
        this.mondifsae = mondifsae;
    }
    public Double getTcambiosae() {
        return this.tcambiosae;
    }
    
    public void setTcambiosae(Double tcambiosae) {
        this.tcambiosae = tcambiosae;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public Integer getConcSae() {
        return this.concSae;
    }
    
    public void setConcSae(Integer concSae) {
        this.concSae = concSae;
    }
    public String getSolicit() {
        return this.solicit;
    }
    
    public void setSolicit(String solicit) {
        this.solicit = solicit;
    }
    public Integer getTransCoi() {
        return this.transCoi;
    }
    
    public void setTransCoi(Integer transCoi) {
        this.transCoi = transCoi;
    }
    public Integer getIntsaenoi() {
        return this.intsaenoi;
    }
    
    public void setIntsaenoi(Integer intsaenoi) {
        this.intsaenoi = intsaenoi;
    }
    public String getXObser() {
        return this.XObser;
    }
    
    public void setXObser(String XObser) {
        this.XObser = XObser;
    }
    public int getFactor() {
        return this.factor;
    }
    
    public void setFactor(int factor) {
        this.factor = factor;
    }
    public int getFormapago() {
        return this.formapago;
    }
    
    public void setFormapago(int formapago) {
        this.formapago = formapago;
    }
    public String getAnombrede() {
        return this.anombrede;
    }
    
    public void setAnombrede(String anombrede) {
        this.anombrede = anombrede;
    }
    public String getAsociado() {
        return this.asociado;
    }
    
    public void setAsociado(String asociado) {
        this.asociado = asociado;
    }
    public String getCtaContabAsoc() {
        return this.ctaContabAsoc;
    }
    
    public void setCtaContabAsoc(String ctaContabAsoc) {
        this.ctaContabAsoc = ctaContabAsoc;
    }
    public Integer getRevisado() {
        return this.revisado;
    }
    
    public void setRevisado(Integer revisado) {
        this.revisado = revisado;
    }
    public String getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(String prioridad) {
        this.prioridad = prioridad;
    }
    public Integer getDocAsoc() {
        return this.docAsoc;
    }
    
    public void setDocAsoc(Integer docAsoc) {
        this.docAsoc = docAsoc;
    }
    public Integer getResaltar() {
        return this.resaltar;
    }
    
    public void setResaltar(Integer resaltar) {
        this.resaltar = resaltar;
    }
    public Integer getAnticipo() {
        return this.anticipo;
    }
    
    public void setAnticipo(Integer anticipo) {
        this.anticipo = anticipo;
    }
    public Integer getIdtransf() {
        return this.idtransf;
    }
    
    public void setIdtransf(Integer idtransf) {
        this.idtransf = idtransf;
    }
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public String getClabe() {
        return this.clabe;
    }
    
    public void setClabe(String clabe) {
        this.clabe = clabe;
    }
    public Integer getMultiClpv() {
        return this.multiClpv;
    }
    
    public void setMultiClpv(Integer multiClpv) {
        this.multiClpv = multiClpv;
    }
    public String getCveBancoAsoc() {
        return this.cveBancoAsoc;
    }
    
    public void setCveBancoAsoc(String cveBancoAsoc) {
        this.cveBancoAsoc = cveBancoAsoc;
    }
    public Integer getNumConcAuto() {
        return this.numConcAuto;
    }
    
    public void setNumConcAuto(Integer numConcAuto) {
        this.numConcAuto = numConcAuto;
    }
    public Integer getCoiDepto() {
        return this.coiDepto;
    }
    
    public void setCoiDepto(Integer coiDepto) {
        this.coiDepto = coiDepto;
    }
    public Integer getCoiCcostos() {
        return this.coiCcostos;
    }
    
    public void setCoiCcostos(Integer coiCcostos) {
        this.coiCcostos = coiCcostos;
    }
    public Integer getCoiProyecto() {
        return this.coiProyecto;
    }
    
    public void setCoiProyecto(Integer coiProyecto) {
        this.coiProyecto = coiProyecto;
    }
    public Set getParmovs04s() {
        return this.parmovs04s;
    }
    
    public void setParmovs04s(Set parmovs04s) {
        this.parmovs04s = parmovs04s;
    }




}


